import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} min-h-screen bg-background text-foreground antialiased md:flex`}>

        <main
          id="main-content"
          className="flex min-h-screen min-w-0 flex-1 flex-col px-4 py-6"
        >
          <Navbar />
          <div className="flex flex-1 flex-col items-center justify-center">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
